apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo
  namespace: workshophubdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-demo
  template:
    metadata:
      labels:
        app: springboot-demo
      annotations:
        timestamp: "2023-10-25T11:07:16Z"
    spec:
      imagePullSecrets:
        - name: dockerhub-regcred
      containers:
      - name: springboot-demo
        image: docker.io/workshophubdev/springboot-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 400m
            memory: 800Mi
