apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo
  namespace: workshophubdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-demo
  template:
    metadata:
      labels:
        app: springboot-demo
      annotations:
        timestamp: "2023-10-27T06:05:56Z"
    spec:
      imagePullSecrets:
        - name: dockerhub-regcred
      containers:
      - name: springboot-demo
        image: docker.io/workshophubdev/springboot-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            cpu: 4000m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 500Mi
