apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: workshophubdev-argocd-route
  namespace: argocd
spec:
  host: ""  
  to:
    kind: Service
    name: argocd-server
    weight: 100
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect